sinks:
  test:
    notion:
      parameters:
        name:
          notionColumnName: Name
          notionColumnType: title
        Surname:
          notionColumnName: Surname
          notionColumnType: text
        age:
          notionColumnName: Person's age
          notionColumnType: number
    webhook:
      url: https://example.com/{{ .name }}
      method: POST
      headers:
        foo: bar
      body: |
        name={{ .name }}&surname={{ .surname }}&age={{ .age  }}
forms:
  www-contact:
    redirect: https://example.com
    inputs:
    - name
    - Surname
    - age
    sinks:
      - test
    captcha:
      enabled: false
