sinks:
  test:
    notion:
      secret: secret_1234567690abcdefghijklmnopqrstuvwxyz1234567
      database: 1234567690abcdefghijklmnopqrstuv
    webhook:
      url: https://example.com/{{ .name }}
      method: POST
      headers:
        foo: bar
      body: |
        name={{ .name }}&surname={{ .surname }}&age={{ .age  }}
forms:
  www-contact:
    redirect: https://example.com
    inputs:
    - Name
    - Surname
    - Age
    sinks:
      - test
    captcha:
      enabled: false
